### ISSUE TITLE
WindowsError: [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by HerendraTJ** [misterch0c/shadowbroker#28]
I have a problem in 64bit PC

Traceback (most recent call last):
  File "fb.py", line 36, in <module>
    from fuzzbunch.edfplugin import EDFPlugin
  File "C:\Users\heren_000\Desktop\NSABACKDOORbyshadowbrokergithub\shadowbroker-
master\windows\fuzzbunch\edfplugin.py", line 7, in <module>
    from plugin       import Plugin
  File "C:\Users\heren_000\Desktop\shadowbroker\windows\fuzzbunch\plugin.py", li
ne 8, in <module>
    import truantchild
  File "C:\Users\heren_000\Desktop\shadowbroker\windows\fuzzbunch\truantchild.py
", line 8, in <module>
    import exma
  File "C:\Users\heren_000\Desktop\shadowbroker\windows\fuzzbunch\exma.py", line
 17, in <module>
    _libraries['exma.dll'] = ctypes.CDLL('exma-1.dll')
  File "C:\Python26\Lib\ctypes\__init__.py", line 353, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

could you tell me why that happened??

**Comment by Ekultek** [comment]
File "C:\Python26\Lib\ctypes_init.py", line 353, in init
self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

That's what happened.

On May 17, 2017, at 06:38 PM, HerendraTJ <notifications@github.com> wrote:

I have a problem in 64bit PC
Traceback (most recent call last):
File "fb.py", line 36, in 
from fuzzbunch.edfplugin import EDFPlugin
File "C:\Users\heren_000\Desktop\NSABACKDOORbyshadowbrokergithub\shadowbroker-
master\windows\fuzzbunch\edfplugin.py", line 7, in 
from plugin import Plugin
File "C:\Users\heren_000\Desktop\shadowbroker\windows\fuzzbunch\plugin.py", li
ne 8, in 
import truantchild
File "C:\Users\heren_000\Desktop\shadowbroker\windows\fuzzbunch\truantchild.py
", line 8, in 
import exma
File "C:\Users\heren_000\Desktop\shadowbroker\windows\fuzzbunch\exma.py", line
17, in 
libraries['exma.dll'] = ctypes.CDLL('exma-1.dll')
File "C:\Python26\Lib\ctypes_init.py", line 353, in init
self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
could you tell me why that happened??

**Comment by HerendraTJ** [comment]
File "C:\Python26\Lib\ctypes_init.py", line 353, in init
self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

How to solve this problem??

**Comment by Ekultek** [comment]
Use Linux

**Comment by HerendraTJ** [comment]
How in windows plz help me
